version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config: 
      config: .eslintrc.json
    checks:
      # compat is not a codeclimeate supported eslint plugin
      compat/compat:
        enabled: false  
exclude_patterns:
  - ".github/"
  - "samples/"
  - "docs/"
  - "utl/"
  - "src/*.js"
  - "src/font"
  - "src/images"
  - "src/lib"
  - "src/test"
  - "src/style"
  - "**/node_modules/"
  - "**/*.d.ts"
