exports.pruimeboom = "De pruimeboom " +
    "Eene vertelling " +
    "\n" +
    "Jantje zag eens pruimen hangen, o! als eieren zo groot. " +
    "'t Scheen, dat Jantje wou gaan plukken, schoon zijn vader 't hem verbood. " +
    "\n\n" +
    "Hier is, zei hij, noch mijn vader, noch de tuinman, die het ziet: " +
    "Aan een boom, zo vol geladen, mist men vijf zes pruimen niet. " +
    "\n\n" +
    "Maar ik wil gehoorzaam wezen, en niet plukken: ik loop heen. " +
    "Zou ik, om een hand vol pruimen, ongehoorzaam wezen? Neen. " +
    "\n\n" +
    "Voord ging Jantje: maar zijn vader, die hem stil beluisterd had, " +
    "Kwam hem in het loopen tegen voor aan op het middelpad. " +
    "\n\n" +
    "Kom mijn Jantje, zei de vader, kom mijn kleine hartedief! " +
    "Nu zal ik u pruimen plukken; nu heeft vader Jantje lief. " +
    "\n\n\n\n\n" +
    "Daar op ging Papa aan 't schudden, Jantje raapte schielijk op; " +
    "Jantje kreeg zijn hoed vol pruimen, en liep heen op een galop.";

exports.pruimeboom_tokenized = ['De', 'pruimeboom',
    'Eene', 'vertelling',
    'Jantje', 'zag', 'eens', 'pruimen', 'hangen,', 'o!', 'als', 'eieren', 'zo', 'groot.',
    '\'t', 'Scheen,', 'dat', 'Jantje', 'wou', 'gaan', 'plukken,', 'schoon', 'zijn', 'vader', '\'t', 'hem', 'verbood.',
    ' ',
    'Hier', 'is,', 'zei', 'hij,', 'noch', 'mijn', 'vader,', 'noch', 'de', 'tuinman,', 'die', 'het', 'ziet:',
    'Aan', 'een', 'boom,', 'zo', 'vol', 'geladen,', 'mist', 'men', 'vijf', 'zes', 'pruimen', 'niet.',
    ' ',
    'Maar', 'ik', 'wil', 'gehoorzaam', 'wezen,', 'en', 'niet', 'plukken:', 'ik', 'loop', 'heen.',
    'Zou', 'ik,', 'om', 'een', 'hand', 'vol', 'pruimen,', 'ongehoorzaam', 'wezen?', 'Neen.',
    ' ',
    'Voord', 'ging', 'Jantje:', 'maar', 'zijn', 'vader,', 'die', 'hem', 'stil', 'beluisterd', 'had,',
    'Kwam', 'hem', 'in', 'het', 'loopen', 'tegen', 'voor', 'aan', 'op', 'het', 'middelpad.',
    ' ',
    'Kom', 'mijn', 'Jantje,', 'zei', 'de', 'vader,', 'kom', 'mijn', 'kleine', 'hartedief!',
    'Nu', 'zal', 'ik', 'u', 'pruimen', 'plukken;', 'nu', 'heeft', 'vader', 'Jantje', 'lief.',
    ' ',
    'Daar', 'op', 'ging', 'Papa', 'aan', '\'t', 'schudden,', 'Jantje', 'raapte', 'schielijk', 'op;',
    'Jantje', 'kreeg', 'zijn', 'hoed', 'vol', 'pruimen,', 'en', 'liep', 'heen', 'op', 'een', 'galop.'];

exports.laozi = "老子《道德經》 第一~四十章\n" +
    "\n" +
    "老子道經\n" +
    "\n" +
    "第一章\n" +
    "\n" +
    "道可道，非常道。名可名，非常名。無，名天地之始﹔有，名萬物之母。\n" +
    "故常無，欲以觀其妙；常有，欲以觀其徼。此兩者，同出而異名，同謂之\n" +
    "玄。玄之又玄，眾妙之門。\n" +
    "\n" +
    "第二章\n" +
    "\n" +
    "天下皆知美之為美，斯惡矣﹔皆知善之為善，斯不善矣。故有無相生，難\n" +
    "易相成，長短相形，高下相傾，音聲相和，前後相隨。是以聖人處「無為\n" +
    "」之事，行「不言」之教。萬物作焉而不辭，生而不有，為而不恃，功成\n" +
    "而弗居。夫唯弗居，是以不去。\n";

exports.laozi_tokenized = ['',
    '老',
    '子《',
    '道',
    '德',
    '經》',
    '第',
    '一~',
    '四',
    '十',
    '章 ',
    '老',
    '子',
    '道',
    '經 ',
    '第',
    '一',
    '章 ',
    '道',
    '可',
    '道，',
    '非',
    '常',
    '道。',
    '名',
    '可',
    '名，',
    '非',
    '常',
    '名。',
    '無，',
    '名',
    '天',
    '地',
    '之',
    '始﹔',
    '有，',
    '名',
    '萬',
    '物',
    '之',
    '母。',
    '故',
    '常',
    '無，',
    '欲',
    '以',
    '觀',
    '其',
    '妙；',
    '常',
    '有，',
    '欲',
    '以',
    '觀',
    '其',
    '徼。',
    '此',
    '兩',
    '者，',
    '同',
    '出',
    '而',
    '異',
    '名，',
    '同',
    '謂',
    '之',
    '玄。',
    '玄',
    '之',
    '又',
    '玄，',
    '眾',
    '妙',
    '之',
    '門。 ',
    '第',
    '二',
    '章 ',
    '天',
    '下',
    '皆',
    '知',
    '美',
    '之',
    '為',
    '美，',
    '斯',
    '惡',
    '矣﹔',
    '皆',
    '知',
    '善',
    '之',
    '為',
    '善，',
    '斯',
    '不',
    '善',
    '矣。',
    '故',
    '有',
    '無',
    '相',
    '生，',
    '難',
    '易',
    '相',
    '成，',
    '長',
    '短',
    '相',
    '形，',
    '高',
    '下',
    '相',
    '傾，',
    '音',
    '聲',
    '相',
    '和，',
    '前',
    '後',
    '相',
    '隨。',
    '是',
    '以',
    '聖',
    '人',
    '處「',
    '無',
    '為',
    '」',
    '之',
    '事，',
    '行「',
    '不',
    '言」',
    '之',
    '教。',
    '萬',
    '物',
    '作',
    '焉',
    '而',
    '不',
    '辭，',
    '生',
    '而',
    '不',
    '有，',
    '為',
    '而',
    '不',
    '恃，',
    '功',
    '成',
    '而',
    '弗',
    '居。',
    '夫',
    '唯',
    '弗',
    '居，',
    '是',
    '以',
    '不',
    '去。',
    ''];
